"""Generate small project-owned simulation meshes with deterministic geometry."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


def write_bowl(path: Path, segments: int = 64) -> None:
    """Write a watertight tapered bowl with a visible cavity and thick rim."""
    rings = (
        (0.030, 0.000),  # outer bottom
        (0.055, 0.055),  # outer rim
        (0.047, 0.052),  # inner rim
        (0.022, 0.012),  # inner floor edge
    )
    vertices: list[tuple[float, float, float]] = []
    for radius, z in rings:
        for index in range(segments):
            angle = 2.0 * np.pi * index / segments
            vertices.append((radius * np.cos(angle), radius * np.sin(angle), z))
    vertices.append((0.0, 0.0, 0.0))
    vertices.append((0.0, 0.0, 0.009))
    outer_floor_center = len(vertices) - 1
    inner_floor_center = len(vertices)
    faces: list[tuple[int, int, int]] = []

    def bridge(first_ring: int, second_ring: int, reverse: bool = False) -> None:
        for index in range(segments):
            following = (index + 1) % segments
            a, b = first_ring * segments + index + 1, first_ring * segments + following + 1
            c, d = second_ring * segments + index + 1, second_ring * segments + following + 1
            faces.extend(((a, b, d), (a, d, c)) if not reverse else ((a, d, b), (a, c, d)))

    bridge(0, 1)  # outer wall
    bridge(1, 2)  # rim
    bridge(2, 3, reverse=True)  # inner wall
    for index in range(segments):
        following = (index + 1) % segments
        faces.append((outer_floor_center, following + 1, index + 1))
        faces.append((inner_floor_center, 3 * segments + index + 1, 3 * segments + following + 1))

    # Tiny simulation meshes are often rendered with back-face culling. Include
    # the opposite winding so both inner and outer bowl walls remain visible.
    faces.extend((c, b, a) for a, b, c in list(faces))

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii") as stream:
        stream.write("# Procedurally generated by scripts/generate_procedural_assets.py\n")
        for vertex in vertices:
            stream.write(f"v {vertex[0]:.7f} {vertex[1]:.7f} {vertex[2]:.7f}\n")
        for face in faces:
            stream.write(f"f {face[0]} {face[1]} {face[2]}\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-root", type=Path, default=Path("assets/procedural"))
    args = parser.parse_args()
    output = args.output_root / "bowl.obj"
    write_bowl(output)
    print(output.resolve())


if __name__ == "__main__":
    main()
